export enum EntityCategoryType {
    Profesionisti     = 0,
    Actori            = 1,
    Independenti      = 2,
    StandUp           = 3,
    Improvizatie      = 4,
    Experimental      = 5,
    Trupa             = 6,
    Tehnicieni        = 7,
    Sunetisti         = 8,
    Luministi         = 9,
    Masinisti         = 10,
    Regizori          = 11,
    Scenaristi        = 12,
    Dansatori         = 13,
    Costumieri        = 14,
    Constructori      = 15,
    Proiectanti       = 16,
    Teatre            = 17,
    DeStat            = 18,
    Independente      = 19,
    Cluburi           = 20,
    Sponsor           = 21
}