import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialMigration1550838213695 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "UserImage" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Image" bytea NOT NULL, "IsProfileImage" boolean NOT NULL, "UserID" uuid, CONSTRAINT "PK_a7b8f73d33c3a99ca1b1145eeb6" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserVideo" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Video" character varying NOT NULL, "UserID" uuid, CONSTRAINT "PK_afe257e031009d04dcdbcf8f3e9" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "SocialMediaCategory" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_cf1d1f90a6fcf11b8f6047fa69b" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserSocialMedia" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "UserID" uuid NOT NULL, "SocialMediaCategoryID" integer NOT NULL, "Link" character varying NOT NULL, CONSTRAINT "PK_f06d4ce569983cf889932e3578c" PRIMARY KEY ("UserID", "SocialMediaCategoryID"))`);
        await queryRunner.query(`CREATE TABLE "Comment" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Content" character varying NOT NULL, "IsApproved" boolean NOT NULL, "UserID" uuid, "WishID" uuid, CONSTRAINT "PK_21c14adde382c15c7fe97377f5b" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "WishCategory" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_de11e450296433ae098f1a0fe41" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Wish" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Title" character varying(100) NOT NULL, "Image" bytea, "Description" character varying NOT NULL, "CanPay" boolean NOT NULL, "IsUrgent" boolean NOT NULL, "WishCategoryID" integer, "UserID" uuid, "SponsorID" uuid, CONSTRAINT "REL_d38aa867d17a9480a366512e6f" UNIQUE ("WishCategoryID"), CONSTRAINT "PK_a870673fc59dce33392385c27a3" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Project" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Name" character varying(100) NOT NULL, "Description" character varying NOT NULL, "Poster" character varying NOT NULL, "Date" TIMESTAMP WITH TIME ZONE NOT NULL, "Price" money, "Link" character varying, CONSTRAINT "PK_8d9b9f2cd4400b2861e2fa3f00d" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserProject" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "MemberID" uuid NOT NULL, "ProjectID" uuid NOT NULL, "IsOwner" boolean NOT NULL, CONSTRAINT "PK_3ec6b563cfc8ec3a7d6ebfd1f5b" PRIMARY KEY ("MemberID", "ProjectID"))`);
        await queryRunner.query(`CREATE TABLE "Message" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Content" character varying NOT NULL, "SenderID" uuid, "RecipientID" uuid, CONSTRAINT "PK_c7c095e348e6c6ba75b06ac2398" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Experience" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Position" character varying(100) NOT NULL, "Employer" character varying(100) NOT NULL, "Description" character varying NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIMESTAMP WITH TIME ZONE NOT NULL, "ProfessionalID" uuid, CONSTRAINT "PK_7daa9b4a1f6cccf187917bc37eb" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Education" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Title" character varying(100) NOT NULL, "Institution" character varying(100) NOT NULL, "Description" character varying NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIMESTAMP WITH TIME ZONE NOT NULL, "ProfessionalID" uuid, CONSTRAINT "PK_d4ffdad99662d98671e73aa200a" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Institution" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Name" character varying(100) NOT NULL, "UserID" uuid, CONSTRAINT "REL_15bc904a0afd5e49c6736426b0" UNIQUE ("UserID"), CONSTRAINT "PK_114f8f0beeb9530b0f1f3a1fb98" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "ProfessionalInstitution" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ProfessionalID" uuid NOT NULL, "InstitutionID" uuid NOT NULL, "IsFounder" boolean NOT NULL, CONSTRAINT "PK_349e1e85dba21dcfedb4ee3f541" PRIMARY KEY ("ProfessionalID", "InstitutionID"))`);
        await queryRunner.query(`CREATE TABLE "Skill" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_4a7680fc6e4ae95640c4290ca9a" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "ProfessionalSkill" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ProfessionalID" uuid NOT NULL, "SkillID" integer NOT NULL, CONSTRAINT "PK_b9f93025c8891c9dbdfc43204fd" PRIMARY KEY ("ProfessionalID", "SkillID"))`);
        await queryRunner.query(`CREATE TABLE "Professional" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "FirstName" character varying(100) NOT NULL, "LastName" character varying(100) NOT NULL, "UserID" uuid, CONSTRAINT "REL_8ed7e58c98b95d0ae3cffaab4f" UNIQUE ("UserID"), CONSTRAINT "PK_454aa355f9b9ff32a15fc74c8e6" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Sponsor" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "UserID" uuid, CONSTRAINT "REL_6d3abbf9e41a3a1e50ec9dd00c" UNIQUE ("UserID"), CONSTRAINT "PK_1b604b98ed2989dcd065cff247e" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserAccountSettings" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "RegistrationIDHash" character varying NOT NULL, "ResetForgottenPasswordIDHash" character varying, "ResetForgottenPasswordExpiration" TIMESTAMP WITH TIME ZONE, "AccountProvider" integer NOT NULL, "AccountStatus" integer NOT NULL, "Role" integer NOT NULL, "EntityCategory" integer NOT NULL, "ProfileVisibility" integer NOT NULL, "EmailVisibility" integer NOT NULL, "BirthDateVisibility" integer NOT NULL, "PhoneNumberVisibility" integer NOT NULL, "UserID" uuid, CONSTRAINT "REL_5a7eb571f0bc1e9de185a6b63d" UNIQUE ("UserID"), CONSTRAINT "PK_9272ecdde0da589d97ea1d2e95d" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "User" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Name" character varying NOT NULL, "Email" character varying(100) NOT NULL, "PasswordHash" character varying NOT NULL, "Description" character varying, "BirthDate" TIMESTAMP WITH TIME ZONE, "PhoneNumber" character varying, "Website" character varying, "ProfileImageID" uuid, CONSTRAINT "REL_6b519da47b33fb18d9db02d97e" UNIQUE ("ProfileImageID"), CONSTRAINT "PK_7c38bb872c3c617c80a311b81d0" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Award" ("DateCreated" TIMESTAMP NOT NULL DEFAULT now(), "DateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "Version" integer NOT NULL, "ID" uuid NOT NULL DEFAULT uuid_generate_v4(), "Title" character varying(100) NOT NULL, "Issuer" character varying(100) NOT NULL, "Description" character varying NOT NULL, "Date" TIMESTAMP WITH TIME ZONE NOT NULL, "UserID" uuid, CONSTRAINT "PK_a6d1e5342f5d7b7633c7b50286a" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "EntityCategory" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, "ParentID" integer, CONSTRAINT "PK_029cde6c720b2d2a0c8a8383f22" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserAccountProvider" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_43e9fba091dc9110517dc37e5d9" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserAccountStatus" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_00e661e287613a84e9146e1791f" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "UserRole" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_446ad4edcf7f1eb13f071de48ed" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`CREATE TABLE "Visibility" ("ID" integer NOT NULL, "Name" character varying(100) NOT NULL, CONSTRAINT "PK_db05b52391276c3e8ee31926c74" PRIMARY KEY ("ID"))`);
        await queryRunner.query(`ALTER TABLE "UserImage" ADD CONSTRAINT "FK_edc0110eaef909032a741341b89" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "UserVideo" ADD CONSTRAINT "FK_e2a8bd0e042103d887e4bfe4b23" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "UserSocialMedia" ADD CONSTRAINT "FK_b5d64292bf3efd4fdcead95ec1d" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "UserSocialMedia" ADD CONSTRAINT "FK_50990c834d8961856f6cca1534e" FOREIGN KEY ("SocialMediaCategoryID") REFERENCES "SocialMediaCategory"("ID")`);
        await queryRunner.query(`ALTER TABLE "Comment" ADD CONSTRAINT "FK_badb25121e5de1057a5bba90b72" FOREIGN KEY ("UserID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "Comment" ADD CONSTRAINT "FK_bfdf9e9294b63e52379e57e4e69" FOREIGN KEY ("WishID") REFERENCES "Wish"("ID")`);
        await queryRunner.query(`ALTER TABLE "Wish" ADD CONSTRAINT "FK_d38aa867d17a9480a366512e6f0" FOREIGN KEY ("WishCategoryID") REFERENCES "WishCategory"("ID")`);
        await queryRunner.query(`ALTER TABLE "Wish" ADD CONSTRAINT "FK_705c738de7a5ca0254586192ca6" FOREIGN KEY ("UserID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "Wish" ADD CONSTRAINT "FK_ca110425dd48512bf3f644d81a2" FOREIGN KEY ("SponsorID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "UserProject" ADD CONSTRAINT "FK_2f7bd8a947358b429eacb576d48" FOREIGN KEY ("MemberID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "UserProject" ADD CONSTRAINT "FK_df1fda4b29398d004d9ad6d5b44" FOREIGN KEY ("ProjectID") REFERENCES "Project"("ID")`);
        await queryRunner.query(`ALTER TABLE "Message" ADD CONSTRAINT "FK_6683962decbc89e4793266df85f" FOREIGN KEY ("SenderID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "Message" ADD CONSTRAINT "FK_0999ae017f57dccd55f9f2ebee1" FOREIGN KEY ("RecipientID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "Experience" ADD CONSTRAINT "FK_e3d40ffc01c63db1d48ea29de0f" FOREIGN KEY ("ProfessionalID") REFERENCES "Professional"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Education" ADD CONSTRAINT "FK_e3909b4a9dd7bd54409cab03980" FOREIGN KEY ("ProfessionalID") REFERENCES "Professional"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Institution" ADD CONSTRAINT "FK_15bc904a0afd5e49c6736426b0c" FOREIGN KEY ("UserID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "ProfessionalInstitution" ADD CONSTRAINT "FK_1ca63a665f05adb720c839b239b" FOREIGN KEY ("ProfessionalID") REFERENCES "Professional"("ID")`);
        await queryRunner.query(`ALTER TABLE "ProfessionalInstitution" ADD CONSTRAINT "FK_98f06fcabb9b12559ba62ac8d21" FOREIGN KEY ("InstitutionID") REFERENCES "Institution"("ID")`);
        await queryRunner.query(`ALTER TABLE "ProfessionalSkill" ADD CONSTRAINT "FK_fb408368042af59a7ff688dd5c5" FOREIGN KEY ("ProfessionalID") REFERENCES "Professional"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ProfessionalSkill" ADD CONSTRAINT "FK_fd463917344b48a4f8baf2e4329" FOREIGN KEY ("SkillID") REFERENCES "Skill"("ID")`);
        await queryRunner.query(`ALTER TABLE "Professional" ADD CONSTRAINT "FK_8ed7e58c98b95d0ae3cffaab4ff" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Sponsor" ADD CONSTRAINT "FK_6d3abbf9e41a3a1e50ec9dd00cf" FOREIGN KEY ("UserID") REFERENCES "User"("ID")`);
        await queryRunner.query(`ALTER TABLE "UserAccountSettings" ADD CONSTRAINT "FK_5a7eb571f0bc1e9de185a6b63df" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "User" ADD CONSTRAINT "FK_6b519da47b33fb18d9db02d97e1" FOREIGN KEY ("ProfileImageID") REFERENCES "UserImage"("ID")`);
        await queryRunner.query(`ALTER TABLE "Award" ADD CONSTRAINT "FK_6b7da3cd0a55b599e7467d6f151" FOREIGN KEY ("UserID") REFERENCES "User"("ID") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "EntityCategory" ADD CONSTRAINT "FK_99e5a7e8a2d8d92733ff7b77016" FOREIGN KEY ("ParentID") REFERENCES "EntityCategory"("ID")`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "EntityCategory" DROP CONSTRAINT "FK_99e5a7e8a2d8d92733ff7b77016"`);
        await queryRunner.query(`ALTER TABLE "Award" DROP CONSTRAINT "FK_6b7da3cd0a55b599e7467d6f151"`);
        await queryRunner.query(`ALTER TABLE "User" DROP CONSTRAINT "FK_6b519da47b33fb18d9db02d97e1"`);
        await queryRunner.query(`ALTER TABLE "UserAccountSettings" DROP CONSTRAINT "FK_5a7eb571f0bc1e9de185a6b63df"`);
        await queryRunner.query(`ALTER TABLE "Sponsor" DROP CONSTRAINT "FK_6d3abbf9e41a3a1e50ec9dd00cf"`);
        await queryRunner.query(`ALTER TABLE "Professional" DROP CONSTRAINT "FK_8ed7e58c98b95d0ae3cffaab4ff"`);
        await queryRunner.query(`ALTER TABLE "ProfessionalSkill" DROP CONSTRAINT "FK_fd463917344b48a4f8baf2e4329"`);
        await queryRunner.query(`ALTER TABLE "ProfessionalSkill" DROP CONSTRAINT "FK_fb408368042af59a7ff688dd5c5"`);
        await queryRunner.query(`ALTER TABLE "ProfessionalInstitution" DROP CONSTRAINT "FK_98f06fcabb9b12559ba62ac8d21"`);
        await queryRunner.query(`ALTER TABLE "ProfessionalInstitution" DROP CONSTRAINT "FK_1ca63a665f05adb720c839b239b"`);
        await queryRunner.query(`ALTER TABLE "Institution" DROP CONSTRAINT "FK_15bc904a0afd5e49c6736426b0c"`);
        await queryRunner.query(`ALTER TABLE "Education" DROP CONSTRAINT "FK_e3909b4a9dd7bd54409cab03980"`);
        await queryRunner.query(`ALTER TABLE "Experience" DROP CONSTRAINT "FK_e3d40ffc01c63db1d48ea29de0f"`);
        await queryRunner.query(`ALTER TABLE "Message" DROP CONSTRAINT "FK_0999ae017f57dccd55f9f2ebee1"`);
        await queryRunner.query(`ALTER TABLE "Message" DROP CONSTRAINT "FK_6683962decbc89e4793266df85f"`);
        await queryRunner.query(`ALTER TABLE "UserProject" DROP CONSTRAINT "FK_df1fda4b29398d004d9ad6d5b44"`);
        await queryRunner.query(`ALTER TABLE "UserProject" DROP CONSTRAINT "FK_2f7bd8a947358b429eacb576d48"`);
        await queryRunner.query(`ALTER TABLE "Wish" DROP CONSTRAINT "FK_ca110425dd48512bf3f644d81a2"`);
        await queryRunner.query(`ALTER TABLE "Wish" DROP CONSTRAINT "FK_705c738de7a5ca0254586192ca6"`);
        await queryRunner.query(`ALTER TABLE "Wish" DROP CONSTRAINT "FK_d38aa867d17a9480a366512e6f0"`);
        await queryRunner.query(`ALTER TABLE "Comment" DROP CONSTRAINT "FK_bfdf9e9294b63e52379e57e4e69"`);
        await queryRunner.query(`ALTER TABLE "Comment" DROP CONSTRAINT "FK_badb25121e5de1057a5bba90b72"`);
        await queryRunner.query(`ALTER TABLE "UserSocialMedia" DROP CONSTRAINT "FK_50990c834d8961856f6cca1534e"`);
        await queryRunner.query(`ALTER TABLE "UserSocialMedia" DROP CONSTRAINT "FK_b5d64292bf3efd4fdcead95ec1d"`);
        await queryRunner.query(`ALTER TABLE "UserVideo" DROP CONSTRAINT "FK_e2a8bd0e042103d887e4bfe4b23"`);
        await queryRunner.query(`ALTER TABLE "UserImage" DROP CONSTRAINT "FK_edc0110eaef909032a741341b89"`);
        await queryRunner.query(`DROP TABLE "Visibility"`);
        await queryRunner.query(`DROP TABLE "UserRole"`);
        await queryRunner.query(`DROP TABLE "UserAccountStatus"`);
        await queryRunner.query(`DROP TABLE "UserAccountProvider"`);
        await queryRunner.query(`DROP TABLE "EntityCategory"`);
        await queryRunner.query(`DROP TABLE "Award"`);
        await queryRunner.query(`DROP TABLE "User"`);
        await queryRunner.query(`DROP TABLE "UserAccountSettings"`);
        await queryRunner.query(`DROP TABLE "Sponsor"`);
        await queryRunner.query(`DROP TABLE "Professional"`);
        await queryRunner.query(`DROP TABLE "ProfessionalSkill"`);
        await queryRunner.query(`DROP TABLE "Skill"`);
        await queryRunner.query(`DROP TABLE "ProfessionalInstitution"`);
        await queryRunner.query(`DROP TABLE "Institution"`);
        await queryRunner.query(`DROP TABLE "Education"`);
        await queryRunner.query(`DROP TABLE "Experience"`);
        await queryRunner.query(`DROP TABLE "Message"`);
        await queryRunner.query(`DROP TABLE "UserProject"`);
        await queryRunner.query(`DROP TABLE "Project"`);
        await queryRunner.query(`DROP TABLE "Wish"`);
        await queryRunner.query(`DROP TABLE "WishCategory"`);
        await queryRunner.query(`DROP TABLE "Comment"`);
        await queryRunner.query(`DROP TABLE "UserSocialMedia"`);
        await queryRunner.query(`DROP TABLE "SocialMediaCategory"`);
        await queryRunner.query(`DROP TABLE "UserVideo"`);
        await queryRunner.query(`DROP TABLE "UserImage"`);
    }

}
